#!/usr/bin/env python

def build(bld):
	lib = bld.new_task_gen('cc', 'shlib')
	lib.source = 'gurl.vala gurl-uri.vala gurl-uri-opener.vala gurl-http.vala gurl-web.vala'
	lib.uselib = 'GNIO GIO GLIB GOBJECT GIO_UNIX'
	lib.uselib_local = 'gnio'
	lib.packages = 'gnio gio-unix-2.0 config'
	lib.target = 'gurl'
	lib.vapi_dirs = '. ../vala'
	bld.install_files('PREFIX', 'share/vala/vapi', 'gurl.vapi')

	module = bld.new_task_gen('cc', 'shlib')
	module.source = 'gurlmodule.vala'
	module.uselib = 'GNIO GIO GLIB GOBJECT GIO_UNIX'
	module.uselib_local = 'gurl gnio'
	module.packages = 'gnio gio-unix-2.0 config gurl'
	module.target = 'gurlmodule'
	module.vapi_dirs = '. ../vala'
	module.includes = '..'
	module.inst_dir = bld.env_of_name('default')['GURL_MODULE_DIR']
#	bld.install_files('PREFIX', 'libgurlmodule.so', bld.env_of_name('default')['GURL_MODULE_DIR'])
