#!/usr/bin/env python

def build(bld):
	for prog in ['test-address', 'test-socket', 'test-resolver', 'test-http']:
		test = bld.new_task_gen('cc', 'program')
		test.uselib_local = 'gnio gurl'
		test.includes = '..'
		test.inst_var = 0
		test.vapi_dirs = '../gurl ../vala'
		test.packages = 'gurl gnio'
		test.source = '%s.vala' % prog
		test.target = prog
		test.unit_test = 1
	
"""
	for prog in ['stuff', 'client', 'server', 'tcp-client']:
		obj = bld.new_task_gen('cc', 'program')
		obj.uselib_local = 'gnio'
		obj.source = '%s.c' % prog
		obj.target = prog
		obj.includes = '..'
		obj.unit_test = 1
		obj.inst_var = 0

	obj = bld.new_task_gen('cc', 'program')
	obj.uselib_local = 'gnio gurl'
	obj.source = 'http.vala'
	obj.target = 'http'
	obj.includes = '..'
	obj.unit_test = 1
	obj.inst_var = 0
	obj.vapi_dirs = '../gurl ../vala'
	obj.packages = 'gurl gnio'

	obj = bld.new_task_gen('cc', 'program')
	obj.uselib = 'GNIO'
	obj.uselib_local = 'gnio'
	obj.source = 'vala-server.vala'
	obj.target = 'vala-server'
	obj.includes = '..'
	obj.unit_test = 1
	obj.inst_var = 0
	obj.vapi_dirs = '../vala'
	obj.packages = 'gnio'
"""
